/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFlashcard: typeof import('./../views/AddFlashcard.vue')['default']
    AddNotification: typeof import('./../components/AddNotification.vue')['default']
    AddToFolder: typeof import('./../components/AddToFolder.vue')['default']
    AppLayout: typeof import('./../layout/AppLayout.vue')['default']
    BottomNavi: typeof import('./../components/BottomNavi.vue')['default']
    CardInput: typeof import('./../components/CardInput.vue')['default']
    CardsFolder: typeof import('./../components/CardsFolder.vue')['default']
    ChooseFolder: typeof import('./../views/ChooseFolder.vue')['default']
    DeleteNotification: typeof import('./../components/DeleteNotification.vue')['default']
    DisplayCard: typeof import('./../components/DisplayCard.vue')['default']
    DisplayFlashcard: typeof import('./../views/DisplayFlashcard.vue')['default']
    DisplayFolder: typeof import('./../views/DisplayFolder.vue')['default']
    FolderDetails: typeof import('./../views/FolderDetails.vue')['default']
    FolderListItem: typeof import('./../components/FolderListItem.vue')['default']
    FolderListItemBundle: typeof import('./../components/FolderListItemBundle.vue')['default']
    FrontPage: typeof import('./../views/FrontPage.vue')['default']
    OpenFolder: typeof import('./../components/OpenFolder.vue')['default']
    PreviousPage: typeof import('./../components/PreviousPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./../components/SearchBox.vue')['default']
  }
}
