/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"arrow_back" | "check_circle_activated" | "check_circle_deactivated" | "delete_card" | "delete_card_red" | "flashcard_logo" | "folder-add" | "folder-fill-all" | "folder-fill-blue" | "folder-fill-orange" | "folder-fill-purple" | "folder-open-fill-all" | "folder-open-fill-blue" | "folder-open-fill-orange" | "folder-open-fill-purple" | "folder_fill" | "folder_line" | "full_circle_folder_blue" | "full_circle_folder_orange" | "full_circle_folder_purple" | "icon-add-fill" | "icon-add-line" | "icon-heart-fill" | "icon-heart-line" | "icon-list-fill" | "icon-list-line" | "remove_card" | "visibility-off" | "visibility">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"arrow_back" | "check_circle_activated" | "check_circle_deactivated" | "delete_card" | "delete_card_red" | "flashcard_logo" | "folder-add" | "folder-fill-all" | "folder-fill-blue" | "folder-fill-orange" | "folder-fill-purple" | "folder-open-fill-all" | "folder-open-fill-blue" | "folder-open-fill-orange" | "folder-open-fill-purple" | "folder_fill" | "folder_line" | "full_circle_folder_blue" | "full_circle_folder_orange" | "full_circle_folder_purple" | "icon-add-fill" | "icon-add-line" | "icon-heart-fill" | "icon-heart-line" | "icon-list-fill" | "icon-list-line" | "remove_card" | "visibility-off" | "visibility">;
            default: string;
            required: true;
        };
    }>>, {
        name: "arrow_back" | "check_circle_activated" | "check_circle_deactivated" | "delete_card" | "delete_card_red" | "flashcard_logo" | "folder-add" | "folder-fill-all" | "folder-fill-blue" | "folder-fill-orange" | "folder-fill-purple" | "folder-open-fill-all" | "folder-open-fill-blue" | "folder-open-fill-orange" | "folder-open-fill-purple" | "folder_fill" | "folder_line" | "full_circle_folder_blue" | "full_circle_folder_orange" | "full_circle_folder_purple" | "icon-add-fill" | "icon-add-line" | "icon-heart-fill" | "icon-heart-line" | "icon-list-fill" | "icon-list-line" | "remove_card" | "visibility-off" | "visibility";
    }>;
  }
}
